spring:
  security:
    cors:
      allowed-origins:
        - https://accountability.jbeauty.uk
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

sentry:
  environment: production
