spring:
  security:
    cors:
      path: /**
      max-age: 3600
      allowed-methods:
        - GET
        - POST
      allowed-headers:
        - Authorization
        - Content-Type
google:
  client-id: ${GOOGLE_CLIENT_ID}
  endpoints:
    user-info: https://www.googleapis.com/oauth2/v3/userinfo
    token-info: https://www.googleapis.com/oauth2/v3/tokeninfo

oauth2:
  mock: false

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
