spring:
  webflux:
    base-path: accountability

  security:
    cors:
      allowed-origins:
        - https://accountability.jbeauty.uk
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}/postgres
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}/postgres
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}