spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://accounts.google.com
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
    cors:
      path: /**
      max-age: 3600
      allowed-origins:
        - https://accountability.jbeauty.uk
      allowed-methods:
        - GET