spring:
  security:
    cors:
      path: /**
      max-age: 3600
      allowed-origins:
        - http://localhost:3000
      allowed-methods:
        - GET
      allowed-headers:
        - Authorization
server:
  error:
    include-message: always

logging:
  level:
    org:
      springframework: trace