spring:
  security:
    cors:
      path: /**
      max-age: 3600
      allowed-origins:
        - https://accountability.jbeauty.uk
      allowed-methods:
        - GET
        - POST
      allowed-headers:
        - Authorization