spring:
  security:
    cors:
      allowed-origins:
        - http://localhost:3000

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

google:
  client-id: ${GOOGLE_CLIENT_ID}