spring:
  security:
    cors:
      path: /**
      max-age: 3600
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers:
        - Authorization
        - Content-Type