FROM eclipse-temurin:17-alpine
COPY ../../build/libs/accountability.jar app.jar

RUN apk update && apk upgrade && apk add curl && rm -rf /var/cache/apk/*

ENV TZONE="Europe/London"
RUN apk add --update tzdata \
&& echo "${TZONE}" > /etc/timezone \
&& ln -sf /usr/share/zoneinfo/${TZONE} /etc/localtime

ENV SPRING_PROFILES_ACTIVE=prod

ENTRYPOINT exec java $JAVA_OPTS -jar app.jar